Repository DerpLab/platform_frameworks_base, pull requests merged in 2020-08, with the labels that each got.

#39 Camera: allow camera to use power key as shutter
  core/java/android/view/Window.java
  core/java/android/view/WindowManager.java
  core/res/AndroidManifest.xml
  services/core/java/com/android/server/policy/PhoneWindowManager.java
  services/core/java/com/android/server/wm/DisplayPolicy.java
Labels: enhancement

#38 FODCircleView: Let us call show() when mIsBouncer() && !isPinOrPattern()
  packages/SystemUI/src/com/android/systemui/biometrics/FODCircleView.java
Labels: enhancement

#41 BatteryService: Add VOOC charging support
  core/java/android/os/BatteryManager.java
  core/res/res/values/aosip_config.xml
  core/res/res/values/aosip_symbols.xml
  packages/SystemUI/res/values/aosip_strings.xml
  packages/SystemUI/src/com/android/keyguard/KeyguardUpdateMonitor.java
  packages/SystemUI/src/com/android/systemui/statusbar/KeyguardIndicationController.java
  services/core/java/com/android/server/BatteryService.java
Labels: enhancement

#43 base: overlays: Add new icon shapes from Android R
  packages/overlays/Android.mk
  packages/overlays/IconShapePebbleOverlay/Android.mk
  packages/overlays/IconShapePebbleOverlay/AndroidManifest.xml
  packages/overlays/IconShapePebbleOverlay/res/values/config.xml
  packages/overlays/IconShapePebbleOverlay/res/values/strings.xml
  packages/overlays/IconShapeTaperedRectOverlay/Android.mk
  packages/overlays/IconShapeTaperedRectOverlay/AndroidManifest.xml
  packages/overlays/IconShapeTaperedRectOverlay/res/values/config.xml
  packages/overlays/IconShapeTaperedRectOverlay/res/values/strings.xml
  packages/overlays/IconShapeVesselOverlay/Android.mk
  packages/overlays/IconShapeVesselOverlay/AndroidManifest.xml
  packages/overlays/IconShapeVesselOverlay/res/values/config.xml
  packages/overlays/IconShapeVesselOverlay/res/values/strings.xml
Labels: enhancement

#46 VibratorService: implement OnePlus proprietary vibrator format
  core/res/res/values/aosip_config.xml
  core/res/res/values/aosip_symbols.xml
  services/core/java/com/android/server/VibratorService.java
Labels: bug

#51 New translation
  packages/SystemUI/res/values-zh-rCN/aosip_strings.xml
Labels: translation
